modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

issueTrackerURL = "https://github.com/HySand/CirCube/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/HySand/CirCube"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="circube.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
authors = "${mod_authors}"
description = '''${mod_description}'''


[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
mandatory = true
versionRange = "[0.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "xaerominimapfair"
mandatory = true
versionRange = "[24.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tacz"
mandatory = true
versionRange = "[1.1.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "infiniverse"
mandatory = true
versionRange = "[1.0.0.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "alexscaves"
mandatory = true
versionRange = "[2.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_connected"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_mobile_packages_unofficial"
mandatory = false
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "protection_pixel"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"